### ISSUE TITLE
Duplicate tabs of login page causes HTTP 400 during login in the second tab

### ISSUE THREAD

**Issue by devJ0n** [IdentityServer/IdentityServer4.Quickstart.UI#31] opened 2017-11-17 12:57 UTC
This is quite a stupid scenario, but it actually happens from time to time among our users. I don't defend the behaivour of our users, but still they continue doing this...

1. Open browser navigate to https://demo.identityserver.io/account/login?returnUrl=%2Fgrants
2. Open another tab and navigate to https://demo.identityserver.io/account/login?returnUrl=%2Fgrants
3. In the first tab enter credentials bob/bob and click login button
4. Wait for login to complete
5. In the second tab enter credentials bob/bob and click login button
6. A response containing 400 Bad Request, a blank page is displayed

If the user refreshes the page or enter the https://demo.identityserver.io/account/login?returnUrl=%2Fgrants URL again, the login form is shown again. If the user enters bob/bob and presss login the https://demo.identityserver.io/grants page is displayed successfully.

Whats causing the HTTP 400 and is there a way to handle this more properly instead of displaying a blank page.

**Comment by brockallen** [comment] 2017-11-17 13:06
> A response containing 400 Bad Request, a blank page is displayed

Possibly the bug in the anti-xsrf token that embeds identity info in it. So once you're logged in the old anti-xsrf token won't work since your identity has changed.

I'll try to repo to confirm it's this issue.

**Comment by brockallen** [comment] 2017-11-19 13:46
Yea, I have confirmed this and it's exactly what I expected:

```
[08:41:16 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: idsrv was successfully authenticated.

[08:41:17 Information] Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter
Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The provided antiforgery token was meant for a different claims-based user than the current user.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()

[08:41:17 Information] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter'.
```

In short, this is not a problem in IdentityServer. It's somewhat of a design flaw in the anti-forgery token plumbing (but they describe it as a feature). I had raised this with @blowdart several years ago when ASP.NET Core was first adding this as a feature. I guess they never tried to address it. Personally, I think it's over aggressive, but who am I?

**Comment by brockallen** [comment] 2017-11-22 16:05
Closing since this is a ASP.NET Core issue and not an IdentityServer issue.

**Closed by brockallen** 2017-11-22 16:05 UTC
Labels: question
